
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Saadettin
 */
public class JAdminPanel extends javax.swing.JFrame {

    CustomerTransaction trans = new CustomerTransaction();
    String ara = "";
    DefaultTableModel accountModel;
    DefaultTableModel customerModel;
    ArrayList<Account> account = trans.hesapGetir();
    ArrayList<Customer> customer = trans.customerGetir();
    public JAdminPanel() {
        initComponents();
        adminName.setText("");
        accountModel = (DefaultTableModel)AccountTable.getModel();
        customerModel = (DefaultTableModel)CustomerTable.getModel();
        accountTableGoster();
        customerTableGoster();
        adminName.setText("Admin");
    }

    public void accountTableGoster(){
        accountModel.setRowCount(0);
        if(account != null){
            for(Account aa : account){
                Object[] adder = {aa.getTC() ,aa.getType(), aa.getAmount(),aa.getIban()};
                accountModel.addRow(adder);
            }
        }
    }
    
    public void customerTableGoster(){
        customerModel.setRowCount(0);
        if(account != null){
            for(Customer aa : customer){
                Object[] adder = {aa.getName(),aa.getTc(), aa.getPhone(),aa.getAdres(), aa.getDate(), aa.getGender(), aa.getId()};
                customerModel.addRow(adder);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AccountTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TCtext = new javax.swing.JTextField();
        TypeText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        AmountText = new javax.swing.JTextField();
        IBANtext = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        dinamikText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerNameText = new javax.swing.JTextField();
        customeTCtext = new javax.swing.JTextField();
        customerGenderText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customerAdressText = new javax.swing.JTextField();
        customerPhoneText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        dinamikAramaCustomer = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        customerConfirmText = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        customerDateChooser = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        adminName = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(182, 237, 233));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(236, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(246, 246, 254));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "T.C", "Type", "Amount", "IBAN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AccountTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(AccountTable);
        if (AccountTable.getColumnModel().getColumnCount() > 0) {
            AccountTable.getColumnModel().getColumn(0).setResizable(false);
            AccountTable.getColumnModel().getColumn(1).setResizable(false);
            AccountTable.getColumnModel().getColumn(2).setResizable(false);
            AccountTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 190, 604, 162));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("T.C");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, 127, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Type");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 105, 127, -1));
        jPanel4.add(TCtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 77, 149, -1));
        jPanel4.add(TypeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 105, 149, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Amount");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 77, 57, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("IBAN");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 105, 57, -1));
        jPanel4.add(AmountText, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 77, 244, -1));
        jPanel4.add(IBANtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 105, 244, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 145, -1, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 145, -1, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton6.setText("Remove");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 145, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Dynamic Search");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, 116, -1));

        dinamikText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dinamikTextKeyReleased(evt);
            }
        });
        jPanel4.add(dinamikText, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 9, 348, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jTabbedPane1.addTab("Accounts List", jPanel2);

        jPanel1.setBackground(new java.awt.Color(236, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "T.C", "Phone", "Adress", "Date of Birth", "Gender", "Confirm"
            }
        ));
        CustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CustomerTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 231, 818, 162));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 80, 127, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("T.C");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, 127, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gender");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 141, 127, -1));

        customerNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextActionPerformed(evt);
            }
        });
        jPanel1.add(customerNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 83, 149, -1));
        jPanel1.add(customeTCtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 113, 149, -1));
        jPanel1.add(customerGenderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 141, 149, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Adress");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 83, 127, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Date of Birth");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 113, 127, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Phone");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 141, 127, -1));
        jPanel1.add(customerAdressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 83, 164, -1));
        jPanel1.add(customerPhoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 141, 164, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 80, 84, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 117, 84, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Dynamic Search");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, 141, -1));
        jPanel1.add(dinamikAramaCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 22, 401, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Confirm");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 169, 127, -1));
        jPanel1.add(customerConfirmText, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 169, 149, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton7.setText("Confirm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 80, -1, -1));
        jPanel1.add(customerDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 113, 164, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 117, 84, -1));

        jTabbedPane1.addTab("Customer List", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 72, 830, 430));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Welcome");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 19, -1, -1));

        adminName.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        adminName.setText(".");
        getContentPane().add(adminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 281, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smoothyBackground.jpg"))); // NOI18N
        background.setText("background");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 880, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccountTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountTableMouseClicked
        int selectRow = AccountTable.getSelectedRow();
        TCtext.setText(AccountTable.getValueAt(selectRow, 0).toString());
        TypeText.setText(AccountTable.getValueAt(selectRow, 1).toString());
        AmountText.setText(AccountTable.getValueAt(selectRow, 2).toString());
        IBANtext.setText(AccountTable.getValueAt(selectRow, 3).toString());
    }//GEN-LAST:event_AccountTableMouseClicked

    private void dinamikTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinamikTextKeyReleased
        ara = dinamikText.getText();
        dinamikAraAccount(ara);
    }//GEN-LAST:event_dinamikTextKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String tc = TCtext.getText();
        if(trans.CustomerName(tc).equals("Bos")){
            JOptionPane.showMessageDialog(null, "Sistemde kaydı olmayan birisine hesap ekleyemezsiniz");
            return;
        }
        String amount = AmountText.getText();
        String type = TypeText.getText();
        String iban = IBANtext.getText();
        if(isEmptyAccount()){
            JOptionPane.showMessageDialog(null, "Lütfen boş kutucukları doldurunuz.");
        }
        else{
            double amount2 = Double.parseDouble(amount);
            trans.addAccount(tc, type, amount2, iban);
            account.add(new Account(type, amount2, iban, tc));
            accountTableGoster();
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String tc = TCtext.getText();
        String amount = AmountText.getText();
        String type = TypeText.getText();
        String iban = IBANtext.getText();
        if(isEmptyAccount()){
            JOptionPane.showMessageDialog(null, "Lütfen boş kutucukları doldurunuz.");
        }
        else{
            double amount2 = Double.parseDouble(amount);
            trans.HesapSil(iban);
            account = trans.hesapGetir();
            accountTableGoster();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String tc = TCtext.getText();
        if(trans.CustomerName(tc).equals("Bos")){
            JOptionPane.showMessageDialog(null, "Sistemde kaydı olmayan şahıslar üzerinden işlem yapamazsınız");
            return;
        }
        String amount = AmountText.getText();
        String type = TypeText.getText();
        String iban = IBANtext.getText();
        if(isEmptyAccount()){
            JOptionPane.showMessageDialog(null, "Lütfen boş kutucukları doldurunuz.");
        }
        else{
            double amount2 = Double.parseDouble(amount);
            trans.AccountGuncelle(tc, type, amount2, iban);
            account = trans.hesapGetir();
            accountTableGoster();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CustomerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTableMouseClicked
        int selectRow = CustomerTable.getSelectedRow();
        customerNameText.setText(CustomerTable.getValueAt(selectRow, 0).toString());
        customeTCtext.setText(CustomerTable.getValueAt(selectRow, 1).toString());
        customerPhoneText.setText(CustomerTable.getValueAt(selectRow, 2).toString());
        customerAdressText.setText(CustomerTable.getValueAt(selectRow, 3).toString());
        Object dateObject = CustomerTable.getValueAt(selectRow, 4); // Object şeklindeki tarih
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Tarih biçimini belirtin

    try {
      Date date = dateFormat.parse(dateObject.toString()); // Object'i Date'e dönüştürün
       customerDateChooser.setDate(date); // Tarihi customerDateChooser bileşenine ayarlayın
    } catch (ParseException e) {
       e.printStackTrace(); // Dönüşüm hatası durumunda hata işleme yapın
    }
        customerGenderText.setText(CustomerTable.getValueAt(selectRow, 5).toString());
        customerConfirmText.setText(CustomerTable.getValueAt(selectRow, 6).toString());
    }//GEN-LAST:event_CustomerTableMouseClicked

    private void customerNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTextActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String confirm = customerConfirmText.getText();
        String tc = customeTCtext.getText();
        if(confirm.equals("1")){
            JOptionPane.showMessageDialog(null, "Onaylanmış hesabı bir daha onaylamaya gerek yok.");
        }
        else{
            trans.customerConfirm(tc);
            customer = trans.customerGetir();
            customerTableGoster();
            JOptionPane.showMessageDialog(null, "Başarıyla onaylandı");
            customerConfirmText.setText("1");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(isEmptyCustomer()){
            JOptionPane.showMessageDialog(null, "Lütfen boş kutucukları doldurunuz.");
        }
        else{
            String tc = customeTCtext.getText();
            trans.deleteCustomer(tc);
            trans.deleteKayitliHesapFull(tc);
            customer = trans.customerGetir();
            customerTableGoster();
            accountTableGoster();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        customer = trans.customerGetir();
        customerTableGoster();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(isEmptyCustomer()){
            JOptionPane.showMessageDialog(null, "Lütfen boş kutucukları doldurunuz.");
            return;
        }
        String tc = customeTCtext.getText();
        if(trans.CustomerName(tc).equals("Bos")){
                JOptionPane.showMessageDialog(null, "Olmayan şahıs üzerinden güncelleme yapamazsınız.");
        }
        else{
            String name = customerNameText.getText();
            String phone = customerPhoneText.getText();
            String gender = customerGenderText.getText();
            String adres = customerAdressText.getText();
            String id2 = customerConfirmText.getText();
            int id = Integer.parseInt(id2);
            Date date = customerDateChooser.getDate();
            trans.CustomerGuncelle(tc, name, phone, gender, adres, id, date);
            
            customer = trans.customerGetir();
            customerTableGoster();
            accountTableGoster();
            JOptionPane.showMessageDialog(null, "Güncelleme başarılı şekilde gerçekleşti.");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public boolean isEmptyCustomer(){
        return customerAdressText.getText().isEmpty() && customerConfirmText.getText().isEmpty() &&
                customerNameText.getText().isEmpty() && customerGenderText.getText().isEmpty() && customerGenderText.getText().isEmpty();
     }
    
    public boolean isEmptyAccount(){
        return TCtext.getText().isEmpty() && AmountText.getText().isEmpty() && TypeText.getText().isEmpty() && IBANtext.getText().isEmpty();
    }
    public void dinamikAraAccount(String ara){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(accountModel);
        AccountTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AccountTable;
    private javax.swing.JTextField AmountText;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JTextField IBANtext;
    private javax.swing.JTextField TCtext;
    private javax.swing.JTextField TypeText;
    private javax.swing.JLabel adminName;
    private javax.swing.JLabel background;
    private javax.swing.JTextField customeTCtext;
    private javax.swing.JTextField customerAdressText;
    private javax.swing.JTextField customerConfirmText;
    private com.toedter.calendar.JDateChooser customerDateChooser;
    private javax.swing.JTextField customerGenderText;
    private javax.swing.JTextField customerNameText;
    private javax.swing.JTextField customerPhoneText;
    private javax.swing.JTextField dinamikAramaCustomer;
    private javax.swing.JTextField dinamikText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
