
import javax.swing.JOptionPane;


public class JChangePassword extends javax.swing.JFrame {

    private String tc = CustomerTransaction.tc;
    CustomerTransaction trans = new CustomerTransaction();
    
    public JChangePassword() {
        initComponents();
        passChangedText.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        oldPassText = new javax.swing.JTextField();
        newPassText = new javax.swing.JTextField();
        newPassText2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        passChangedText = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Eski Şifre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 98, 106, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Yeni Şifre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 138, 106, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Yeni Şifre (tekrar)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 178, 130, -1));

        oldPassText.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                oldPassTextCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                oldPassTextİnputMethodTextChanged(evt);
            }
        });
        getContentPane().add(oldPassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 95, 120, -1));

        newPassText.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                newPassTextİnputMethodTextChanged(evt);
            }
        });
        getContentPane().add(newPassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 135, 120, -1));

        newPassText2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                newPassText2İnputMethodTextChanged(evt);
            }
        });
        newPassText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassText2ActionPerformed(evt);
            }
        });
        getContentPane().add(newPassText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 175, 120, -1));

        jButton1.setBackground(new java.awt.Color(100, 199, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("Şifre Değiştir");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 120, 40));

        passChangedText.setForeground(new java.awt.Color(255, 0, 0));
        passChangedText.setText(".");
        getContentPane().add(passChangedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 215, 261, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pastel-clouds-presentation-background-slides.jpg"))); // NOI18N
        background.setText("jLabel4");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 310, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String old = oldPassText.getText();
        String neww = newPassText.getText();
        String neww2 = newPassText2.getText();
        if( !( trans.getPassword(tc).equals(old) ) ){
                passChangedText.setText("Eski şifreyi yanlış girdiniz");
                return;
            }
        if(! ( neww.equals(neww2) ) ){
            passChangedText.setText("Yeni şifre ile Tekrar girdiğiniz yeni şifre uyuşmuyor");
            return;
        }
        if(old.length() != 0 && neww.length() != 0 && neww2.length() != 0){
            trans.changedPassword(tc, neww);
            setVisible(false);
            JOptionPane.showMessageDialog(null, "Şifreniz değişti");
        }
        else{
            passChangedText.setText("Lütfen boşlukları doldurunuz...");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void oldPassTextCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_oldPassTextCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPassTextCaretPositionChanged

    private void oldPassTextİnputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_oldPassTextİnputMethodTextChanged
        passChangedText.setText("");
    }//GEN-LAST:event_oldPassTextİnputMethodTextChanged

    private void newPassTextİnputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_newPassTextİnputMethodTextChanged
        passChangedText.setText("");
    }//GEN-LAST:event_newPassTextİnputMethodTextChanged

    private void newPassText2İnputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_newPassText2İnputMethodTextChanged
        passChangedText.setText("");
    }//GEN-LAST:event_newPassText2İnputMethodTextChanged

    private void newPassText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassText2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField newPassText;
    private javax.swing.JTextField newPassText2;
    private javax.swing.JTextField oldPassText;
    private javax.swing.JLabel passChangedText;
    // End of variables declaration//GEN-END:variables
}
