
import javax.swing.JOptionPane;

/**
 *
 * @author Saadettin
 */
public class JLogin extends javax.swing.JFrame {

    CustomerTransaction trans = new CustomerTransaction();
    
    public JLogin() {
        initComponents();
        trans.back();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tc = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        entry = new javax.swing.JButton();
        registration = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("T.C Kimlik No:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 330, 120, 18));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Kullanıcı Şifresi:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 359, 120, -1));

        tc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tc.setBorder(new javax.swing.border.MatteBorder(null));
        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });
        getContentPane().add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 140, 30));

        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 140, 30));

        entry.setBackground(new java.awt.Color(255, 204, 204));
        entry.setText("Giriş");
        entry.setBorder(new javax.swing.border.MatteBorder(null));
        entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryActionPerformed(evt);
            }
        });
        getContentPane().add(entry, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 117, 24));

        registration.setBackground(new java.awt.Color(255, 204, 204));
        registration.setText("Müşteri Kaydı ");
        registration.setBorder(new javax.swing.border.MatteBorder(null));
        registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationActionPerformed(evt);
            }
        });
        getContentPane().add(registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 114, 24));

        message.setForeground(new java.awt.Color(255, 0, 51));
        message.setText("Lütfen bilgilerinizi giriniz...");
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 234, -1));

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x40wzghtg8tpctaz04q0.png"))); // NOI18N
        jLabel3.setText("   KAPSÜL BANK");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 13, 530, 309));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pastel-clouds-presentation-background-slides.jpg"))); // NOI18N
        background.setText("jLabel4");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryActionPerformed
        message.setText("");
        String tcc = tc.getText();
        String pass = new String(password.getPassword());
        if(isEmptyTextLogin()){
            message.setText("Bilgilerinizi eksik girdiniz");
        }
        else if( trans.girisYap(pass, tcc) ) {
            message.setText("Giriş başarılı");
            String name = trans.CustomerName(tcc);
            System.out.println(name);
            trans.isaretle(name, tcc);
            trans.isaretle( tcc);
            setVisible(false);
            JCustomerPanel jCustomer = new JCustomerPanel();
            jCustomer.setVisible(true);
            
            
        }
        else{
            message.setText("Giriş başarısız");
        }
            
        
        
    }//GEN-LAST:event_entryActionPerformed

    public boolean isEmptyTextLogin(){
       String pass = new String(this.password.getPassword());
       if(tc.getText().length() != 0 && pass.length() != 0)
            return false;
       return true;
   }
    private void registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationActionPerformed
        JRegistration reg = new JRegistration(this, true);
        setVisible(false);
        reg.setVisible(true);
    }//GEN-LAST:event_registrationActionPerformed

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton entry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel message;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registration;
    private javax.swing.JTextField tc;
    // End of variables declaration//GEN-END:variables
}
