
import java.util.Calendar;
import java.util.Date;


public class JRegistration extends javax.swing.JDialog {

    CustomerTransaction trans = new CustomerTransaction();
    
    public JRegistration(){}
    public JRegistration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    void approved(){
        Kvkk_info.setSelected(true);
        this.toFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        messageText = new javax.swing.JLabel();
        dateReg = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        passwordText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        soyadText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        Kvkk_info = new javax.swing.JCheckBox();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Cinsiyetiniz");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 293, 123, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 130, 244, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 210, 244, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz...", "Erkek", "Kadın", "Seçimsiz" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 290, 124, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("İsim");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 53, 123, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("T.C kimlik no:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 133, 123, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Telefon Numarası");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 213, 123, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Doğum tarihiniz");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 250, 123, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kaydol");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 514, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Temizle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 514, -1, -1));

        messageText.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        messageText.setForeground(new java.awt.Color(255, 102, 0));
        messageText.setText("Bilgileri eksiksiz bir şekilde giriniz....");
        getContentPane().add(messageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 428, 370, -1));
        getContentPane().add(dateReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 250, 244, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 388, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Adres");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 330, 117, -1));

        jTextPane1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 330, 244, 80));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Geri");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 514, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Parola");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 173, 123, -1));
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 170, 244, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Soyad");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 93, 123, -1));
        getContentPane().add(soyadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 90, 244, -1));
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 50, 244, -1));

        Kvkk_info.setFont(new java.awt.Font("Constantia", 2, 12)); // NOI18N
        Kvkk_info.setText("Aydınlatma metnini ve KVKK bilgilendirme metnini okudum, onaylıyorum");
        Kvkk_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kvkk_infoActionPerformed(evt);
            }
        });
        getContentPane().add(Kvkk_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 461, 410, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smoothyBackground.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            messageText.setText("Bilgileri eksiksiz bir şekilde giriniz....");
            nameText.setText("");
            soyadText.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextPane1.setText("");
            passwordText.setText("");
            jComboBox1.setSelectedItem("Seçiniz...");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        messageText.setText("");
        String name = nameText.getText() + " "+soyadText.getText();
        String tc = jTextField2.getText();
        String phone = jTextField3.getText();
        String gender = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        String adres = jTextPane1.getText();
        String pass = passwordText.getText();
        if(!isEmptyText()){
            Calendar calendar = dateReg.getCalendar();
            Date date = calendar.getTime();
            trans.addCustomer(name, tc, phone, gender, date, adres, pass);
            messageText.setText("İsteğiniz başarılı şekilde ulaştı");
        }
        else
            messageText.setText("Lütfen bilgilerinizi eksiksiz giriniz!!!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        new JLogin().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Kvkk_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kvkk_infoActionPerformed
        KVKKinfo kvk = new KVKKinfo(this);
        kvk.setVisible(true);
        this.toBack();
        this.setVisible(false);
        kvk.toFront();
        
    }//GEN-LAST:event_Kvkk_infoActionPerformed
    public boolean isEmptyText(){
       String gender = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
       return !(soyadText.getText().length() != 0 &&passwordText.getText().length() != 0 && dateReg.getCalendar() != null && nameText.getText().length() != 0 && jTextField2.getText().length() != 0 && jTextField3.getText().length() != 0 && !gender.equals("Seçiniz...") && jTextPane1.getText().length() != 0 && Kvkk_info.isSelected());
   }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JRegistration dialog = new JRegistration(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Kvkk_info;
    private javax.swing.JLabel background;
    private com.toedter.calendar.JDateChooser dateReg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel messageText;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField passwordText;
    private javax.swing.JTextField soyadText;
    // End of variables declaration//GEN-END:variables
}
